// <auto-generated />
using System;
using CuidandoDoMeuCarro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CuidandoDoMeuCarro.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240213142351_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("CuidandoDoMeuCarro.Models.Carro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnoFabricacao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnoModelo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoFipe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MontadoraId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MotoristaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MontadoraId");

                    b.HasIndex("MotoristaId");

                    b.ToTable("Carros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnoFabricacao = 2018,
                            AnoModelo = 2018,
                            CodigoFipe = "023140-1",
                            Cor = "Prata",
                            Modelo = "Versa",
                            MontadoraId = 1,
                            MotoristaId = 1,
                            Placa = "ABC1D234"
                        },
                        new
                        {
                            Id = 2,
                            AnoFabricacao = 2019,
                            AnoModelo = 2021,
                            CodigoFipe = "054409-7",
                            Cor = "Vermelho",
                            Modelo = "MOBI",
                            MontadoraId = 3,
                            MotoristaId = 2,
                            Placa = "VDA0E751"
                        });
                });

            modelBuilder.Entity("CuidandoDoMeuCarro.Models.Manutencao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarroId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ManutencaoCorretiva")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Quilometragem")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarroId");

                    b.ToTable("Manutencoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarroId = 1,
                            Data = new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Troca de óleo",
                            ManutencaoCorretiva = false,
                            Quilometragem = 70251L,
                            Valor = 258.21m
                        },
                        new
                        {
                            Id = 2,
                            CarroId = 1,
                            Data = new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Troca de Filtros",
                            ManutencaoCorretiva = false,
                            Quilometragem = 70251L,
                            Valor = 115.50m
                        },
                        new
                        {
                            Id = 3,
                            CarroId = 1,
                            Data = new DateTime(2023, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Troca de Velas",
                            ManutencaoCorretiva = true,
                            Quilometragem = 80557L,
                            Valor = 321.99m
                        },
                        new
                        {
                            Id = 4,
                            CarroId = 1,
                            Data = new DateTime(2023, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Troca de Pastilhas de Freio",
                            ManutencaoCorretiva = true,
                            Quilometragem = 85521L,
                            Valor = 299.99m
                        },
                        new
                        {
                            Id = 5,
                            CarroId = 2,
                            Data = new DateTime(2023, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Troca de óleo",
                            ManutencaoCorretiva = false,
                            Quilometragem = 52225L,
                            Valor = 199.99m
                        },
                        new
                        {
                            Id = 6,
                            CarroId = 2,
                            Data = new DateTime(2023, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Troca de Filtros",
                            ManutencaoCorretiva = false,
                            Quilometragem = 52225L,
                            Valor = 99.99m
                        },
                        new
                        {
                            Id = 7,
                            CarroId = 2,
                            Data = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Troca da Correia Dentada",
                            ManutencaoCorretiva = true,
                            Quilometragem = 60002L,
                            Valor = 517.25m
                        });
                });

            modelBuilder.Entity("CuidandoDoMeuCarro.Models.Montadora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Montadoras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Marca = "Nissan"
                        },
                        new
                        {
                            Id = 2,
                            Marca = "Volkswagen"
                        },
                        new
                        {
                            Id = 3,
                            Marca = "Fiat"
                        },
                        new
                        {
                            Id = 4,
                            Marca = "GM"
                        },
                        new
                        {
                            Id = 5,
                            Marca = "Ford"
                        });
                });

            modelBuilder.Entity("CuidandoDoMeuCarro.Models.Motorista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Cnh")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoCNH")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ValidadeCnh")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Motoristas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cnh = 1234567890L,
                            Nome = "Antonio Souza",
                            TipoCNH = 4,
                            ValidadeCnh = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Cnh = 7894561230L,
                            Nome = "Daniela Campos",
                            TipoCNH = 2,
                            ValidadeCnh = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Cnh = 5201789652L,
                            Nome = "Eduardo Souza",
                            TipoCNH = 1,
                            ValidadeCnh = new DateTime(2026, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CuidandoDoMeuCarro.Models.Carro", b =>
                {
                    b.HasOne("CuidandoDoMeuCarro.Models.Montadora", "Montadora")
                        .WithMany("Carros")
                        .HasForeignKey("MontadoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CuidandoDoMeuCarro.Models.Motorista", "Motorista")
                        .WithMany("Carros")
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Montadora");

                    b.Navigation("Motorista");
                });

            modelBuilder.Entity("CuidandoDoMeuCarro.Models.Manutencao", b =>
                {
                    b.HasOne("CuidandoDoMeuCarro.Models.Carro", "Carro")
                        .WithMany("Manutencoes")
                        .HasForeignKey("CarroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carro");
                });

            modelBuilder.Entity("CuidandoDoMeuCarro.Models.Carro", b =>
                {
                    b.Navigation("Manutencoes");
                });

            modelBuilder.Entity("CuidandoDoMeuCarro.Models.Montadora", b =>
                {
                    b.Navigation("Carros");
                });

            modelBuilder.Entity("CuidandoDoMeuCarro.Models.Motorista", b =>
                {
                    b.Navigation("Carros");
                });
#pragma warning restore 612, 618
        }
    }
}
