// <auto-generated />
using System;
using CuidandoDoMeuCarro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CuidandoDoMeuCarro.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("CuidandoDoMeuCarro.Models.Carro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnoFabricacao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnoModelo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoFipe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MontadoraId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MotoristaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MontadoraId");

                    b.HasIndex("MotoristaId");

                    b.ToTable("Carros");
                });

            modelBuilder.Entity("CuidandoDoMeuCarro.Models.Manutencao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarroId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ManutencaoCorretiva")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProximaQuilometragem")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Quilometragem")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarroId");

                    b.ToTable("Manutencoes");
                });

            modelBuilder.Entity("CuidandoDoMeuCarro.Models.ManutencaoCarro", b =>
                {
                    b.Property<int>("CarroId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManutencaoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CarroId", "ManutencaoId");

                    b.ToTable("ManutencoesCarro");
                });

            modelBuilder.Entity("CuidandoDoMeuCarro.Models.Montadora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Montadoras");
                });

            modelBuilder.Entity("CuidandoDoMeuCarro.Models.Motorista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Cnh")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoCNH")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ValidadeCnh")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Motoristas");
                });

            modelBuilder.Entity("CuidandoDoMeuCarro.Models.Carro", b =>
                {
                    b.HasOne("CuidandoDoMeuCarro.Models.Montadora", "Montadora")
                        .WithMany("Carros")
                        .HasForeignKey("MontadoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CuidandoDoMeuCarro.Models.Motorista", "Motorista")
                        .WithMany("Carros")
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Montadora");

                    b.Navigation("Motorista");
                });

            modelBuilder.Entity("CuidandoDoMeuCarro.Models.Manutencao", b =>
                {
                    b.HasOne("CuidandoDoMeuCarro.Models.Carro", "Carro")
                        .WithMany("Manutencoes")
                        .HasForeignKey("CarroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carro");
                });

            modelBuilder.Entity("CuidandoDoMeuCarro.Models.Carro", b =>
                {
                    b.Navigation("Manutencoes");
                });

            modelBuilder.Entity("CuidandoDoMeuCarro.Models.Montadora", b =>
                {
                    b.Navigation("Carros");
                });

            modelBuilder.Entity("CuidandoDoMeuCarro.Models.Motorista", b =>
                {
                    b.Navigation("Carros");
                });
#pragma warning restore 612, 618
        }
    }
}
